openapi: 3.0.0
info:
    title: Groove
    version: "1.0"

paths:
    /api/v1/auth/sign-up:
        post:
            tags:
                - Auth
            summary: sign up request
            description: sign up request
            operationId: sign_up
            requestBody:
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/sign-up-request"
                required: true
            responses:
                "201":
                    description: Created
                    content:
                        application/json; charset=utf-8:
                            schema:
                                allOf:
                                    - $ref: "#/components/schemas/sign-up-response"
    /api/v1/auth/login:
        post:
            tags:
                - Auth
            summary: login request
            description: login request
            operationId: login
            requestBody:
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/login-request"
                required: true
            responses:
                "200":
                    description: Login successful
                    content:
                        application/json; charset=utf-8:
                            schema:
                                allOf:
                                    - $ref: "#/components/schemas/login-response"

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    schemas:
        sign-up-request:
            title: SignUpRequest
            required:
                - firstName
                - lastName
                - email
                - username
                - password
                - confirmPassword
            type: object
            properties:
                firstName:
                    type: string
                lastName:
                    type: string
                email:
                    type: string
                username:
                    type: string
                password:
                    type: string
                confirmPassword:
                    type: string
        sign-up-response:
            title: SignUpResponse
            type: object
            required:
                - success
                - data
                - token
            properties:
                success:
                    type: boolean
                token:
                    type: string
                data:
                    allOf:
                        - $ref: "#/components/schemas/user-response-data"
                        - {}
        login-request:
            title: LoginRequest
            required:
                - email
                - password
            type: object
            properties:
                email:
                    type: string
                password:
                    type: string
        login-response:
            title: LoginResponse
            required:
                - success
                - data
                - accessToken
                - refreshToken
            type: object
            properties:
                success:
                    type: boolean
                data:
                    allOf:
                        - $ref: "#/components/schemas/user-response-data"
                        - {}
                accessToken:
                    type: string
                refreshToken:
                    type: string
        user-response-data:
            title: UserResponseData
            type: object
            required:
                - id
                - firstName
                - lastName
                - email
                - username
                - role
                - password
                - resetPasswordToken
                - resetPasswordExpires
                - createdAt
                - updatedAt
            properties:
                id:
                    type: integer
                    format: int32
                firstName:
                    type: string
                lastName:
                    type: string
                email:
                    type: string
                username:
                    type: string
                role:
                    type: string
                resetPasswordToken:
                    nullable: true
                resetPasswordExpires:
                    nullable: true
                createdAt:
                    type: string
                updatedAt:
                    type: string

tags:
    - name: Auth
