openapi: 3.0.0
info:
    title: Groove
    version: "1.0"

paths:
    /api/v1/auth/sign-up:
        post:
            tags:
                - auth
            requestBody:
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/sign-up-request"
                required: true
            responses:
                "201":
                    description: CREATED
                    content:
                        application/json; charset=utf-8:
                            schema:
                                allOf:
                                    - $ref: "#/components/schemas/sign-up-response"
    /api/v1/auth/login:
        post:
            tags:
                - auth
            requestBody:
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/login-request"
                required: true
            responses:
                "200":
                    description: OK
                    content:
                        application/json; charset=utf-8:
                            schema:
                                allOf:
                                    - $ref: "#/components/schemas/login-response"
    /api/v1/auth/forgot-password:
        post:
            tags:
                - auth
            requestBody:
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/forgot-password-request"
                required: true
            responses:
                "200":
                    description: OK
                    content:
                        application/json; charset=utf-8:
                            schema:
                                allOf:
                                    - $ref: "#/components/schemas/forgot-password-response"
    /api/v1/auth/reset-password:
        patch:
            tags:
                - auth
            parameters:
                - in: query
                  name: token
                  schema:
                      type: string
                      description: token for reset password
                  
            requestBody:
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/reset-password-request"
                required: true
            responses:
                "200":
                    description: OK
                    content:
                        application/json; charset=utf-8:
                            schema:
                                allOf:
                                    - $ref: "#/components/schemas/reset-password-response"
    /api/v1/users/profile/get-my-profile:
        get:
            tags:
                - user
            responses:
                "200":
                    description: OK
                    content:
                        application/json; charset=utf-8:
                            schema:
                                allOf:
                                    - $ref: "#/components/schemas/profile-response"
            security: [{ bearerAuth: [] }]
    /api/v1/users/profile/update-my-profile:
        patch:
            tags:
                - user
            requestBody:
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/update-my-profile-request"
            responses:
                "200":
                    description: OK
                    content:
                        application/json; charset=utf-8:
                            schema:
                                allOf:
                                    - $ref: "#/components/schemas/profile-response"
            security: [{ bearerAuth: [] }]

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    schemas:
        sign-up-request:
            title: SignUpRequest
            type: object
            required:
                - firstName
                - lastName
                - email
                - username
                - password
                - confirmPassword
            properties:
                firstName:
                    type: string
                lastName:
                    type: string
                email:
                    type: string
                username:
                    type: string
                password:
                    type: string
                confirmPassword:
                    type: string
        sign-up-response:
            title: SignUpResponse
            type: object
            required:
                - success
                - data
                - accessToken
            properties:
                success:
                    type: boolean
                data:
                    allOf:
                        - $ref: "#/components/schemas/user-response-data"
                        - {}
                accessToken:
                    type: string
        login-request:
            title: LoginRequest
            type: object
            required:
                - email
                - password
            properties:
                email:
                    type: string
                password:
                    type: string
        login-response:
            title: LoginResponse
            type: object
            required:
                - success
                - data
                - accessToken
            properties:
                success:
                    type: boolean
                data:
                    allOf:
                        - $ref: "#/components/schemas/user-response-data"
                        - {}
                accessToken:
                    type: string
        user-response-data:
            title: UserResponseData
            type: object
            required:
                - id
                - firstName
                - lastName
                - email
                - username
                - role
                - password
                - resetPasswordToken
                - resetPasswordExpires
                - createdAt
                - updatedAt
            properties:
                id:
                    type: integer
                    format: int32
                firstName:
                    type: string
                lastName:
                    type: string
                email:
                    type: string
                username:
                    type: string
                role:
                    type: string
                resetPasswordToken:
                    nullable: true
                resetPasswordExpires:
                    nullable: true
                createdAt:
                    type: string
                updatedAt:
                    type: string
        forgot-password-request:
            title: ForgotPasswordRequest
            type: object
            required:
                - email
            properties:
                email:
                    type: string
        forgot-password-response:
            title: ForgotPasswordResponse
            type: object
            required:
                - success
                - message
            properties:
                success:
                    type: boolean
                message:
                    type: string
        reset-password-request:
            title: ResetPasswordRequest
            type: object
            required:
                - email
                - password
                - confirmPassword
            properties:
                email:
                    type: string
                password:
                    type: string
                confirmPassword:
                    type: string
        reset-password-response:
            title: ResetPasswordResponse
            type: object
            required:
                - success
                - message
            properties:
                success:
                    type: boolean
                message:
                    type: string
        profile-response:
            title: GetMyProfileResponse
            type: object
            required:
                - success
                - data
            properties:
                success:
                    type: boolean
                data:
                    allOf:
                        - $ref: "#/components/schemas/user-response-data"
                        - {}
        update-my-profile-request:
            title: UpdateMyProfileRequest
            type: object
            properties:
                firstName:
                    type: string
                lastName:
                    type: string
                email:
                    type: string
                username:
                    type: string

tags:
    - name: auth
    - name: user
